author: cscanlin
title: cscanlin.github.io
domain: cscanlin.github.io
theme: jekyll-theme-cayman
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'site_builder_node.js']

# Site Builder
screenshot_directory: ./assets/images/screenshots/
screenshot_width: 1280
screenshot_height: 800
repositories:
  - repo_url: https://github.com/cscanlin/munger-builder
    screenshot_target: http://www.mungerbuilder.com/script_builder/pivot_builder/1

  - repo_url: https://github.com/cscanlin/choice-optimizer
    screenshot_height: 650

  - repo_url: https://github.com/cscanlin/generator-pages-project-gallery
    screenshot_target: https://cscanlin.github.io/

  - repo_url: https://github.com/cscanlin/films_api
    screenshot_target: https://films-api.herokuapp.com/films/

  - repo_url: https://github.com/cscanlin/minesweeper
    screenshot_height: 450

  - repo_url: https://github.com/cscanlin/periodic-table-timeline
