title: cscanlin.github.io
theme: jekyll-theme-slate
screenshot_directory: ./assets/images/screenshots/
screenshot_width: 1280
screenshot_height: 800
repositories:
  - repo_url: https://github.com/cscanlin/munger-builder
    screenshot_target: http://www.mungerbuilder.com/script_builder/pivot_builder/1

  - repo_url: https://github.com/cscanlin/choice-optimizer

  - repo_url: https://github.com/cscanlin/pages-project-gallery
    screenshot_target: https://cscanlin.github.io/

  - repo_url: https://github.com/cscanlin/films_api
    screenshot_target: https://films-api.herokuapp.com/films/

  - repo_url: https://github.com/cscanlin/minesweeper

  - repo_url: https://github.com/cscanlin/periodic-table-timeline
